apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagaautodeploy
  labels:
    app: nagaautodeploy
    kubernetes.azure.com/generator: devhub
  namespace: naganamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nagaautodeploy
  template:
    metadata:
      labels:
        app: nagaautodeploy
    spec:
      containers:
        - name: nagaautodeploy
          image: nagatestdevopsregistry.azurecr.io/image-workflow-1734115256129:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
