apiVersion: v1
kind: Service
metadata:
  name: nagaautodeploy
  namespace: naganamespace
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: nagaautodeploy
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000